version: '3.4'
services:
  mindoc:
    image: registry.cn-hangzhou.aliyuncs.com/mindoc/mindoc:v2.0-beta.2
    container_name: mindoc
    restart: always
    ports: 
      - 8098:8181
    volumes: 
      - /data/mindoc/database:/mindoc/database
      - /data/mindoc/uploads:/mindoc/uploads
    environment: 
      MINDOC_RUN_MODE: prod
      MINDOC_DB_ADAPTER: sqlite3
      MINDOC_DB_DATABASE: ./database/mindoc.db
      MINDOC_CACHE: 'true'
      MINDOC_CACHE_PROVIDER: file
      MINDOC_ENABLE_EXPORT: 'true'
      