version: '3.4'
services:
  freshrss:
    image: freshrss/freshrss:1.25.0
    container_name: freshrss
    restart: always
    ports:
      - 8282:80
    environment:
      TZ: Asia/Shanghai
      CRON_MIN: '*/45'  # RSS刷新周期，单位：分钟
      MYSQL_HOST: 172.17.0.1:3306
      MYSQL_DATABASE: freshrss
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions