version: '3.4'
services:
  postgres:
    image: postgres:9.5
    container_name: pgsql
    restart: always
    ports: 
      - 5432:5432
    volumes: 
      - /data/pgsql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    networks: 
      - devops-network

networks: 
  devops-network:
    external: true