version: '3.4'
services: 
  redis:
    image: library/redis:5.0.12
    container_name: redis
    restart: always
    ports: 
      - 6379:6379
    command: redis-server --requirepass 123456 --appendonly yes
    volumes: 
      - /data/redis/data:/data
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - devops-network

networks: 
  devops-network:
    external: true