version: '3.4'
services: 
  mariadb:
    image: mariadb:10.5.6
    container_name: mariadb
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    restart: always
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: bing
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
      TIMEZONE: Asis/Shanghai
    volumes: 
      - /data/mysql/data:/var/lib/mysql
      - /data/mysql/conf:/etc/mysql/conf.d
      - /etc/localtime:/etc/localtime:ro